apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatchsim-backend-config
  namespace: dispatchsim
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-prod.database.svc.cluster.local:3306/dispatch_sim?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "dispatchsim_prod"
  SPRING_DATA_REDIS_HOST: "redis-prod.cache.svc.cluster.local"
  SPRING_RABBITMQ_HOST: "rabbitmq-prod.mq.svc.cluster.local"
  SPRING_RABBITMQ_USERNAME: "dispatchsim"
