apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dispatchsim.fullname" . }}-backend-secret
  namespace: {{ include "dispatchsim.namespace" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.backend.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
