sonar.projectKey=dispatchsim-backend
sonar.projectName=dispatch-sim-backend
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.exclusions=src/main/java/**/dto/**,src/main/java/**/config/**,src/main/java/**/domain/model/**,src/main/java/**/domain/event/**
