apiVersion: v1
kind: Secret
metadata:
  name: dispatchsim-backend-secret
  namespace: dispatchsim
stringData:
  SPRING_DATASOURCE_PASSWORD: "replace-dev-password"
  SPRING_RABBITMQ_PASSWORD: "replace-dev-password"
